//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP.Seguros.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poliza()
        {
            this.ClientePolizas = new HashSet<ClientePoliza>();
        }
    
        public int IdPoliza { get; set; }
        public int IdTipoPoliza { get; set; }
        public System.DateTime Inicio { get; set; }
        public int Duracion { get; set; }
        public string Precio { get; set; }
        public int IdTipoRiesgo { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientePoliza> ClientePolizas { get; set; }
        public virtual Tipo_Poliza Tipo_Poliza { get; set; }
        public virtual Tipo_Riesgo Tipo_Riesgo { get; set; }
    }
}
